services:
  app:
    build: .
    container_name: gh-api-data-fetch
    ports:
      - "8080:8080"
    command: ./server
    restart: always
    volumes:  
      - .:/gh-api/

    env_file:
            - ./config/dev.env